# Generated by Django 5.1.6 on 2025-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
            ],
        ),
    ]
